### ISSUE TITLE
TypeError on readArmored run in node.js

### ISSUE THREAD

**Issue by JimBeam2019** [openpgpjs/openpgpjs#1108]
Hi there,

I was trying one of the samples that Streaming encrypts and decrypts String data with PGP keys in a node.js project, and below is my code in the PgpController class.

 ```
    const passphrase = 'super long and hard to guess secret';
    const { privateKeyArmored, publicKeyArmored } = await openpgp.generateKey({
      userIds: [{ name: 'Jon Smith', email: 'jon@example.com' }],
      rsaBits: 2048,
      passphrase
    });

    const privateKey = (await openpgp.key.readArmored(privateKeyArmored))
      .keys[0];
    await privateKey.decrypt(passphrase);

    const readableStream = new ReadableStream({
      start(controller) {
        controller.enqueue('Hello world!');
        controller.close();
      }
    });

    const { data: encrypted } = await openpgp.encrypt({
      message: openpgp.message.fromText(readableStream),
      publicKeys: (await openpgp.key.readArmored(publicKeyArmored)).keys,
      privateKeys: [privateKey]
    });

    console.log('Encrypted text >>>>>> ', encrypted);

    const { data: decrypted } = await openpgp.decrypt({
      message: await openpgp.message.readArmored(encrypted.data),
      publicKeys: (await openpgp.key.readArmored(publicKeyArmored)).keys,
      privateKeys: [privateKeyArmored]
    });

    const plainText = await openpgp.stream.readToEnd(decrypted.data);

    console.log('Decrypted text : ', plainText);
```

But when it runs, the code returns the type error below.

```
(node:7664) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'readArmored' of undefined
    at _callee2$ (/media/jimbeam/DATA1/Software/Projects/test_ground/Controller/PgpController.js:53:43)
    at tryCatch (/media/jimbeam/DATA1/Software/Projects/test_ground/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/media/jimbeam/DATA1/Software/Projects/test_ground/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/media/jimbeam/DATA1/Software/Projects/test_ground/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/media/jimbeam/DATA1/Software/Projects/test_ground/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/media/jimbeam/DATA1/Software/Projects/test_ground/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

I was wondering if there is anything wrong with my code. Please give me any advice, thank you.

**Comment by twiss** [comment]
Hey :wave: How are you importing openpgp?

**Comment by JimBeam2019** [comment]
Hi Daniel,

I'm using ES 6, and import the openpgp as below.

import openpgp from 'openpgp';

Warm regards,

Jinbin

________________________________

**Comment by twiss** [comment]
Hey :wave: Please try:

```js
import * as openpgp from 'openpgp';
```

**Comment by JimBeam2019** [comment]
> Hey wave Please try:
> 
> ```js
> import * as openpgp from 'openpgp';
> ```

Thanks. It works like a charm.
