### ISSUE TITLE
bpg key? 

### ISSUE THREAD

**Issue by vejandla** [openpgpjs/openpgpjs#1127]
I was give an *.bpg (file extension) public key and asked to encrypt a json data using gpg encryption. I'm currently using nodejs and explored openpgpjs and node-gpg and not able to find any methods or examples that talk about using key with extension bpg

I tied opening bpg, it seems binary. How can read the binary key and encrypt json payload to unit8array? 

appreciate help.

**Comment by twiss** [comment]
Hey :wave: If it's simply a binary PGP key, you could use `openpgp.key.read`.

**Comment by vejandla** [comment]
Tried reading the key this way, 

```js

const openpgp = require("openpgp");
const fs = require("fs");

var key = fs.readFileSync("key.bpg", "utf8");

// var cipher = gpg.encrypt(encrypt.recipients, encrypt.content);
(async () => {
  const keys = await openpgp.key.read(key);
  console.log(keys);
})();

```

i see the below error in the keys.error :( 

stack:'Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.\n    at Object.read (/Users/Aslesh/Code/tryouts/node-gpg-test/node_modules/openpgp/dist/openpgp.js:38897:15)\n    at async /Users/Aslesh/Code/tryouts/node-gpg-test/node_modules/openpgp/dist/openpgp.js:39145:22'

**Comment by vejandla** [comment]
Hi @twiss Thanks for the reply, I was able to get the key information. 

```js

const openpgp = require("openpgp");
const fs = require("fs");

(async () => {
  var key = await fs.readFileSync("pub.bpg");
  const keys = await openpgp.key.read(key);
  const readableStream = new ReadableStream({
    start(controller) {
      controller.enqueue(JSON.stringify({ test: "test" }));
      controller.close();
    },
  });
  const encrypted = await openpgp.encrypt({
    message: openpgp.message.fromText(readableStream),
    publicKeys: keys,
  });
  console.log(keys);
})();
```

I'm just trying to encrypt the json payload. Followed the documentation and when I run the above code, I am seeing this error. 

```error
(node:31644) UnhandledPromiseRejectionWarning: TypeError: Error encrypting message: key.getPrimaryUser is not a function
    atnode_modules/openpgp/dist/openpgp.js:33989:35
    at Array.map (<anonymous>)
    at getPreferredAlgo (node_modules/openpgp/dist/openpgp.js:33988:26)
    at Message.encrypt (node_modules/openpgp/dist/openpgp.js:36352:96)
    at /node_modules/openpgp/dist/openpgp.js:37253:20
    at /index.js:13:21
```

Here is the Keys info, I've retrieved from reading the binary file.

![image](https://user-images.githubusercontent.com/3577997/88297903-7d8ddd80-ccce-11ea-9f72-79d9c518944a.png)

**Comment by twiss** [comment]
Hey :wave: You have to pass the keys array, inside the object, not the object itself.

**Comment by vejandla** [comment]
Yeah, Just realized and came here to convey the same. Thanks again for quick response.

**Comment by vejandla** [comment]
@twiss, Just curious, Can the encrypted data directly outputs as buffer or byte array?

**Comment by twiss** [comment]
Yes, see the first half of this example for inspiration: https://github.com/openpgpjs/openpgpjs#encrypt-and-decrypt-uint8array-data-with-a-password

Btw, it seems like you used a streaming example, but you can also just pass a string to `fromText` directly, you don't have to create a stream object.

**Comment by vejandla** [comment]
Thanks @twiss , 

I was trying out options. yes, eventually used From text, To retrieve the encryped data in the binary format, I tried this from the examples you have referred. 

```js

const openpgp = require("openpgp");
const fs = require("fs");

var JsonToArray = function (json) {
  var str = JSON.stringify(json, null, 0);
  var ret = new Uint8Array(str.length);
  for (var i = 0; i < str.length; i++) {
    ret[i] = str.charCodeAt(i);
  }
  return ret;
};

(async () => {
  var key = await fs.readFileSync("pub.bpg");
  const keys = (await openpgp.key.read(key)).keys;
  const data = await openpgp.encrypt({
    message: openpgp.message.fromBinary(JsonToArray({ test: "test" })),
    publicKeys: keys,
  });
  console.log(data);
})();

```

I still do not see the encrypted `data` as array.

**Comment by twiss** [comment]
Hey :wave: That's not the part of the example I meant :D You can use `fromText`. Try passing `armor: false` and calling `data.message.packets.write()`.

**Comment by vejandla** [comment]
Perfect!! Thanks again for quick response.

**Comment by vejandla** [comment]
``` js
// encrypting using the json payload. Is there anything I'm doing wrong here? receiving end is always failing to decrypt, aways a bad request

const pgpEncrypt = async (payload) => {
  var encryptedKey = await fs.readFileSync("pub.bpg");
  const keys = (await openpgp.key.read(encryptedKey)).keys;
  const data = await openpgp.encrypt({
    message: openpgp.message.fromText(JSON.stringify(payload, null, 0)),
    publicKeys: keys,
    armor: false,
  });
  return data.message.packets.write();
};

const formData = new FormData();
let fileContent = await pgpEncrypt(customPayload);
let stream = bufferToStream(Buffer.from(fileContent));
formData.append("file", stream);

const { Readable } = require("stream");
function bufferToStream(binary) {
  const readableInstanceStream = new Readable({
    read() {
      this.push(binary);
      this.push(null);
    },
  });
  return readableInstanceStream;
}

axios.post(url, formData, {
        headers: {
         ...formData.getHeaders(),
          Authorization: `Bearer ${accessToken}`,
        },
      })
    );
```

**Comment by vejandla** [comment]
Is there a way we can get a simple text key from the binary key? would it be possible?

**Comment by twiss** [comment]
Yes, once you've parsed the key, you can do `key.armor()`. Regarding the code, I don't know much about the axios library, but the openpgp.js code looks fine to me.

**Comment by vejandla** [comment]
Thanks @twiss, This encryption thing is totally new to me. I was given that binary key and the below article to encrypt json payload. I'm not sure whether this library is what I should be using or something else. The names are totally confusing.. and very little information in the wild for newbies. 

https://www.ibm.com/support/knowledgecenter/SS4T5W/Watson_Talent_Data_Management_Administrator_Guide/gnupg_to_import_pgp_keys.html

Is the this library I should using for what was mentioned in above link?

**Comment by twiss** [comment]
It's possible to do it using openpgp.js, although the above instructions are for gnupg. Since openpgp.js is a library and gnupg is an application, I would try to do it using gnupg, since it's probably easier, unless you have a specific reason not to.

**Comment by vejandla** [comment]
ahhh !! 🤯 I have this feeling all along that this could not be this complicated unless I'm doing different encryption all along.

I've been using opepgpjs as I've to do this using nodejs service, so, just looked for the package to do (gnupg) and npm gave this as a popular library.

**Comment by twiss** [comment]
Ah yeah. If it's in a node.js service then openpgp.js is definitely appropriate. Nevertheless, if you find it easier using gnupg you can also hack something together by calling gnupg from node.js of course. But it wasn't really meant to be used as a library instead of an application.

**Comment by vejandla** [comment]
So to conclude, If the client is expected to encrypt in GnuPG, I cannot use openpgp.js or the way I was encrypting here? https://github.com/openpgpjs/openpgpjs/issues/1127#issuecomment-663242769  Is this a right assumption? @twiss

**Comment by twiss** [comment]
No, openpgp.js and gnupg are compatible. You should be able to achieve what you want with openpgp.js.

**Comment by vejandla** [comment]
```js

const pgpEncrypt = async (payload) => {
  var encryptedKey = await fs.readFileSync("pub.bpg");
  const keys = (await openpgp.key.read(encryptedKey)).keys;
  const data = await openpgp.encrypt({
    message: openpgp.message.fromText(JSON.stringify(payload, null, 0)),
    publicKeys: keys,
    armor: false,
  });
  return data.message.packets.write();
};

// after encryption, If I have to write the content to a file, Is there a built-in method to it or can I just write it this way?

let filename = '../uniquid.gpg';
fs.writeFileSync(filename, fileContent);
```

after encryption, If I have to write the content to a file, Is there a built-in method to it or can I just write it the above way? 

I wanted to eliminate `Axios` and see if I can post the file through postman manually to corner the problem to find out if encryption is the problem or the way I was posting data to API is a problem.

**Comment by vejandla** [comment]
@twiss **I guess I found the problem**, but I do not know the solution. Hoping you can guide me in this. 

when we encrypted the message what we are seeing on the top of the encrypted message is like below.. 

```
-----BEGIN PGP MESSAGE-----
Version: OpenPGP.js v4.10.7
Comment: https://openpgpjs.org
```

But, when we used the application `gnupg` the encrypted file contains this on top of the message. and in the file as version 

`Version: BCPG v1.61`

So, I took the public key by doing, `console.log(keys[0].armor())` and and encrypted my json payload using this website and manually posted it, it worked for me. But I'm not sure how to do this using this library. Thanks in advance.

https://8gwifi.org/pgpencdec.jsp

PUBLIC KEY:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v4.10.7
Comment: https://openpgpjs.org

xsBNBF8GwnUBCADQWERxa5HKvsrilGzd1V6GAXGBadTdAfvIKnl3FU+w9A68
gM3hgQI4dkL6c40wWh0B93X6G91LOao8v3QaER2XXY6o4WhwINP9CjiKRsff
PPMWOtnnHA3SkoHTpRrM7csUrW1etEuupJ1uSVbu4WFnvpLfsAPgkZzk5OX3
wd8RhlwRO+oY7Q1KnAK9Hv2T1U/iJQSL49axo81J1/68E24Ct6PB7uKr3ytP
Q7NMuywgeYvZs4AM336bEXTWSRbUKuxgheQP7EM14lsYobs+jAcB6xd6GNgB
oLt6SIsfTKO6BmyClrCsda6u7/lTXy+P8JONO6/StVMVY0Nx7cZ68vDxABEB
AAHNI0RhbmllbCBIdXNlciA8ZGFuaWVsLmh1c2VyQHNhcC5jb20+wsBtBBMB
CgAXBQJfBsJ1AhsvAwsJBwMVCggCHgECF4AACgkQEB3N424D+buvHwf/f34h
XHPrdmQzK3Zk84X3rq+DUFaN4qvIMDqvPpj4kyKovo5mCFQ0as+Hy3Fricp0
onrB3j4zz01Z9xMzStVYIIoCNtW6RYFozpK9Fahp1C93iI8eoI3pV9aMTI84
MUU0a/xn3ak00FmD3J/mmBV76aGtotpu9Ceed75Fewn3Qu6WpRRFLOzm97z4
wVPR4qvMirbOBuS8L1d9QWGXGBX64wA725J0IL0UVycW8ce7jatZR9VD+Mn7
RT0sfYBT+UTBrnrq8sU/nMeZjh9q+Kq6+Mhotv4ewJaLncnkDb45gtpJG7Tt
ScyT4FLWgBC/0GWJKrfGVFhByqA2Yo9TVD2Nls7ATQRfBsJ1AQgAxbjmNLTB
J7A+2CpVppxxAYX1Y8ZfB98GxL2QKdWXzACoJYc42qf08bINKoDxJBrJneoG
sfo+rZhHKawPWJSi13sYiUa6VTvUQo6lU+cAOA5QgHole7EKmgVf8p2P/eiV
SQBDco+uafyIXMXyrMxP7jlUOO8ud8y3tRNEgeOhXTAoMooW6ud7Frt/GDBK
xLSH1tJs9NmTvyW75iR+I/fUpR8i20pyBYFSpNTHbTahAbpkIjFrbraZ+0Og
Dwj9W2WhlrehaO0FfJnpan4Mq391KVbqNdXhhXv9kwno2iD+8Z5XPRa46n0H
sCa7QYFmTutV+/wvZQzQ/qKNDee8m6nXxQARAQABwsGEBBgBCgAPBQJfBsJ1
BQkPCZwAAhsuASkJEBAdzeNuA/m7wF0gBBkBCgAGBQJfBsJ1AAoJEMQwy2yh
oHZ2CrUIAIyPX0HAknaAk+owZck5in8WBPYJK3itJ+zTfBtDcQv9LaUBGuZ0
mHkMSyjt18edpqrTBxGV+XvivU66qCpMcKPcFJh2JngPNpPbIKVn8zJ2r0EX
7gvKfK7Sbd7Ki9Xs91XvmM7LDI5yomxu8rJxRlpZkYvrm1+Cjsu0nWjl6usM
ysvQU9rUyi1Z5SmBG6S1jN+2e8TprO6oTgPFTJZ2GiLVBN4Rg0mgt/S/k3yF
NvL24M1+iM3vd4yfCmpzyrcyywiFeq7IF1DorC9yR+1BTittdAJWG+TKhR+O
Av0vB3iDtqaioPRkkhcm43qUusvyIMSyBv9C0jl6cXeKw373oKSW3Af/QDl/
1YD/XUjWLqxirAV5Gnk/3fEHE/eQrpDMM9Ddqg3dTZ//+NfFkkOg4bIiVz3s
GpL3LBpoxN9gcJ4J+croXeLs7BR8xeponXs54ql0EulhOy5FTPKNelgeCWbT
VlOigSjQ3yqeGlOitY1R81FrEjt/Hoep2GEwupCGVtNHc/zecufC8L2qNln/
5t/4V81dlj2E00zuyr/RhhUc2lHjHJUIsfGsKAQQUTlmQorKxdkEAElNUn/P
lKN8RwAJkm6h7v759B6WVtiJXRVFRq7U4ZgGM73LPT59BQcV3ev1IZEaA+Oy
HqXZ48ldS8xsgKqFmyvqR6bkMRDSPgcsOFVQNs7ATQRfBsJ1AQgApQDMPdit
90zkL4Xx/H0AT7d/7rn0O33PqMfLRNvkog88C0+rFojKU7km0T27qNZggdbU
94xhYDXx6pGxcWc6oexY+UYPLI3e0XDZebozb2iqsGgF7xgLw+DuICvwu91z
tX0RkqMvz7QcV04XmZht6ioLPWxZqOtxN2vxVforqofVwOq10t8ijZkMC/1I
lhNKsmFtbDf6iTXRUWXBpaVjuk5xq/lcqle8Cc0f22S/kVwOiucSCqJLsWzs
wx/XWsuT9pzI1hZBOqQ9lQCt1HcuY6emLv7LeOBlM+8uZJDim/NEPoJNONzS
RrhEnYgG12I+EOmJFkvEz/3kzrNyUZ6xAwARAQABwsGEBBgBCgAPBQJfBsJ1
BQkPCZwAAhsuASkJEBAdzeNuA/m7wF0gBBkBCgAGBQJfBsJ1AAoJEKlgbISK
JDGzmd4H/Rb2WkmuiYbGbf1BThH/0J0BXtcomzRtYTKlHi+NdIi2fKn0C8+V
QQtc27Mgxr5hQFhl3fJPhi1J0oAVe2ftgOYY4UySmvHF2IDosFWYzaFKBQJe
SQlwLLKAnByATpR6IApsJnZtMU37oMjspcvvXuWtimoOidOYzx85eUS11uEu
3U6z4Ae4GXKL/h6vc7syAkj3VEegHDOoZlsPULSpEdYRfK1hB/0mt2Isbg0q
9mrBOzsr43gER5o+7JSgXUQrRTPXSE50xDmqAkEcTc1KuIZ1lpEPCWSoYdzA
pNe15VtiWQjNFAS95P3JWxMHE19L4bJXaaNX2zIsXiZ4havExpi6uQf+Jbqz
qU+AC4RKUd+rpS7VVKTQoXPlfcgIlEn0j0yH6xxbMwGNc+Bg+NCIhmUz0wSH
u1NNA4UVl5LAnE+b+p6Nk5wLj/V+E9hmbnbVAQ9RtH2vDa/7dOzhi71B2qQJ
Dl9DOM/dbHtjZW8ttwbJsAeeUe5bJBwilGWnftF+18LCMuu/fzqU58zNBBbF
6GWAGIgRlq+uS7So+5OGfe33MFahGZlRM/UKTXGThp/F8krEUu+G8EaYdDPE
Q8xUySCRoMQKfOmiD4o/3ZbKvGMdPExQBLjU4czB8CXnR1Afwi6R+bkCOwM5
GoGRTpQUPNv3XkD8/iZD6sUx0obz5y8ORZKDSQ==
=GGoJ
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by vejandla** [comment]
@tomholub any idea? Thanks in advance.

**Comment by twiss** [comment]
@vejandla The different comment header shouldn't make a difference. There might be some other difference between the messages though.

However, have you tried just manually submitting a message you encrypted using openpgp.js? Did it work? What error did you get? Etc.

**Comment by vejandla** [comment]
Yes, I have. the API is alway getting bad request. 

The same public key, I encrypted the json payload and got the below as encrypted content posted, got bad request.
and also, took the public key, encrypted at this website https://8gwifi.org/pgpencdec.jsp and posted this content, it is working.

```js
var encryptedKey = await fs.readFileSync("public-key.gpg");
  const keys = (await openpgp.key.read(encryptedKey)).keys;
  const { data: encrypted } = await openpgp.encrypt({
    message: openpgp.message.fromText(JSON.stringify(payload, null, 0)),
    publicKeys: keys,
  });
```

encrypted content using openpgp.
```
-----BEGIN PGP MESSAGE-----
Version: OpenPGP.js v4.10.7
Comment: https://openpgpjs.org

wcBMA8Qwy2yhoHZ2AQgArOYqoW3lWmFRO6CH6vqETPygPgnB/AiA32MjKP7L
C64Tg0yrilAJZxgeEfY7iQ3Qm+fpbID/Cwdeyu2bS8KY8Kb5SpJ60OMSKEfH
ugbakyHbCbPEWTFgkF/2L0VDyFpOtiXgKL3nrmmZkBjgUYevix/4T5oF2KRr
9iFjaLSlVuZ+1VaGt6eX04CwYomhrASybhZUyEULRXqx04NQS9lVOMx+nlya
P9aKCrRRIWx7t11tcACSkd5Glk5IGWKPwQB3/7OsmX6+ZGwp/WNAevGJ9kcP
4fsUHdT0+DF6JR26Ku2exgCJtxsButbk+fGz097qCZuLc7fLg5Lzge5rlSRn
zdLGNgGgP7NMvpwpKtIsxGzTXmLRkSH4D+IVwrW6WE0N3NdR82ThQdUAYsh+
/gELjuKtIB3ueGBMlXQb7jQ0VqBfzTnlcOsEUD+UzAqCAg5t7IUrIefusdQO
//S7/1Hy8Cr3ADmve4WXxP0yelPdbtgaKtDe/HuGm1uOVxHDbCSEcWbHkF61
Ul8j6HUdz7d1fti9r+fxE7iiQRDjeOax1pPgAX06sDDJ1S6pthtl2vjYs6Xe
55wNIDS+MdIWgYs/nS8NVItJLwY7Z6vsB8QRtNU85lCvVST8e5m/iMUN94fU
44TJS/UTJaG+RWUeY0xkEy/KA4ECjqy64GLgG0t+PV0phdgBMnf/SkOgIOHW
AgetjWdqrxpVx2CVlvv7lpUV7vjIjkKDNgMyMckb9RwieddaEHhCOE/vE2Tf
2aZPBYR8cPwONWaaQ2qsptQSgoEFIj79gmJh8U7GTXjVflVppZQSy9CDyoZ/
Swx+qk2iKN76sYJds+AKsHqh6DVweiGfGrgvZJRj7D7kk+RrUloW1T0c6RRI
fNvBrUZTbpTHUBr6SgDfsfSJNc3vn6jOm8iPH6RFFfD2U+hmPlIe5qlPnClp
EHUOVh+/FLGqJAAOPGcSeyRhi1LM+f/17HKByM2HSmmQ3nANsYoUvgkQjzLb
1rNwWi4t4TkXtepWh+LwGXwjOAUMjoVWeTNcUp9BPKV0nNWZk1L+u8JHoz+I
F/lDybnks+FD3s01QRI7iHrKrZCXnX/WAu8ZW0LyjaxN5TCh9+qPbAWMdliW
sAqoFuAqE4SJHlw2rvwqJqT2C+eNtwX6I0II+ad9tnEdyXZM6duV9Wd6IlYW
Ybx+LsgMg52c1/PV3P3VrSq5jGY7BBBFR/p6H4p+0j+yn6R2wC1YIg4sO31t
0LFJJleVd4hzHKvtX3tzN/W6w//Tq3H69NIBzDLJRbk5unmOB6QbDUI/H4vh
U7bDT3vLYRRu1Wvoh41Rh12aWxDlcW1C9D+N2oF4TNJpL0HwApwG0tX1h5PB
NTGcICi1B9sdEiij9lwMAS9gxWI0lv/APIb7yLNIGqNSq/M3JqMWRNVjA9Mr
9zuFdLZIJ1IWr5oP5f0ZApcyVZxM+zmKbQ//t1lGA0DCzYFnRADQlnQSBj6b
vpAL+vZTlBsIyLRj0AUa0+uFOnnde3F1R5CJvbQWFkG/6QJUj1sxjOTY1yxw
yH7nsuQilVWMr9nGleDgE9rcWNURWYbaJpnlkRuYkiseDCeIKEIWgXqK3VH3
WRWQa2efxFbbk0tPVbVas4szGIWe2Eu31q4wGa1SFMwERPqx24AGgnuivA7q
rDjS2B8HKqTF1/or5qmHZFfhttfyl1m4vfvhnm7R6rjpfFVOuvu4Tvkp/+tq
XBwT1A3QK8q66zR1p94/h/chqkb7KIuTWcA3ZgZEd9bKTA/rb9hjW1B2DGyZ
2lFE0K1xPmGL86R8XlMevni7Oy6oZe/oEcBLvONMz5bahWrmsbWGHQyji656
RrwRAxX3Y9VjRD7w8zThzjfHMzH7uCxwJnvZDHbgnfs2uIzicsDt7ZWEFWWt
7U/WZNqkKBiWHqA9qV8Ds8NpsTULJoBdR+va220HORl2HAa7JTt6dhTItXgq
zvBuP6qdJ52p1m30iD5Ryd2tjh5InB2HHXj5w5ki/SJWjNVeBRCJlGdmIu4C
v1c7kmSV/vs99CRD8ejwm/w/gqB2Rn99HeKd+uVEwrm4k5WY2Tkn0P7LwvNA
ZLZAuisbAgz5jvUg/nmrMqMgFNTUijl/kvWMulu5miUkvCrXAsQBSsinxznP
fImNSgaTFXlISJLIkWxtolcyrbM/uoeNBu/SVbBes3xCZWPNgau1q/Pr/PBl
3uX2GMC0osEO755Ac8n6RtZchazG60aD7zW+Ujy4dLzYFmoUBXb1K6UOilOl
4OH6Obzzi48tJEdtWakzukX2W5oJwUnqZ9fiwSJKLqs7H+1wF7Dp6UVv8fXT
GOpHYX9fqXjsEUcpj1MesKAqtpB/mOQCXcFYZrLJ7XlaIw3bgSYyxz9WzA5+
S2gpkWBhlzivAy0Xd4YEAFqo1+FZ6FlTrFwZQZ0WHfwQEPj2I14ICayJtr+/
zIQ+8WOP6Jz3U0enrESvx/rseUtmT4yn+EGy28RZGpDRAG4sFRQOytBjqpsG
jWL5l+t/Df1bBkdSBhqFQtJ1BhbPEvp8B2R/5K+B0YTwOSVMxjRGJw+SJ/sw
lljVl3BPxm1y7Akis/44fGfEuMFFkWCN/p+jk9L9K+aG88yNkdEwTcwmNu+b
GE7HWhI1ng5/rvXIHx70gwuGTfNW4xUJawN91X+c7gJv7drLFeqZRmEjb9Hy
VzciG+bZpYUqHjTerEc+zN3C07D70bSd9IsH1xK5tQ==
=nme3
-----END PGP MESSAGE-----
```

encrypted content at website https://8gwifi.org/pgpencdec.jsp

```

-----BEGIN PGP MESSAGE-----
Version: BCPG v1.58

hQEMAxAdzeNuA/m7AQf/fyYUDOIZbnWmOezntJRqYHAyudufMDaBJpsiyWpiL9zX
XDP2ATmhVFrAapHcvmMh0EN9SpkZyi4CTVFmVto/f9w6WtAF0cfSXHn5X64t6ll0
AHzT05mS2kM2rbqVcOrlptTx/TVyMM70E/loScIWJKZJYHOO37EPwYgMavORSEFb
S6jP7AxLIGQlOeP5to2QVYTrE42H7SgIeD/8mT79WhKlb24rplKufFBxrg/LvUai
JFdZCMDPPN8RylUVWigjx4imC1xSi0HRvjkvJ5lEgf+Ktu8iswvjS9RV4di2uLiG
Hc9G6MgnBYNpVFuJioi73gsjKOM6miFpLcvMdF73+dLCcAE+eg/CIrekf741GtwP
Ljg1wTTZk87pm35k0krmH6k01TIqOShOarG8U9ZNrCpk0mGtpxK9yMRBmM5bQ3vN
xeh5RskFJThFpf3zqhi0XXs1y+9dQWgwvv/BlAmpHDiCw9RbKdnwI9uP3xdE/Dd6
xw4Iwyjg0TjYu9qHQF40PRgnK2e0gfcC5s5N4MCPp81kbelXtTyWVGCFDN39+VN3
7zzTGbLF+iTA+EYVnYBNqFHho3dfQXJlHSxsljatJ98DShMM6y/vO9wlFoPUrvvW
11i6pJxcbHW7Lyucv6Ih0ksnHF83cE4XAqzTleyUCUtjMZV2MZLYj6Rx3DEYxsoK
dds078qdoO5dPo7OyGGNxWWtfhXOJVs1FYGeOPwBNXGJ4ECvAKlYHQBwtG2odM3r
GKJtgMx3e8eAHIU8puvJOia+y4a0KnljOn0ObIfJP1cRaZwqHtYK2Y+sYqBsmkRW
mqXeAr1PLq2jB0pwvZLLcUhEmwJ1nGsHKSgqzxfceTC96y4fSpqDSLMGxMj2wzwv
po/c4DxOhIZU3+pfFns2Jj2I6c9Waj2boz8NKzQiPTHP863h5WnAhCT2fH8NGolf
DBoLMvKr3tHQaWnK145iaKf5tvbVhjVE51ciK1brtNO7Ih3TvO/OhQHY8bAeAecX
Ex72h1BO3nd39MeOHJWe5FaFV4sIFFsQON2dmFFVGF/YU7goceMT9IYQAs6nIroc
gvWFiVlK191KXrZIVoJ7M7iFFXva2e5eBg9/GX4iawiaHInMjw2hTRYwImk3AwLh
BJ0X19bqEOLOuf26EihV5eEVA4Aq91eYQoPQMufwOkSjjNDRttDypilC24eeedOy
xpw/NQ8PvzX3Yqco/WpqspR3Zuu53UEiqarK9HahheZJ2j1vq726O4iyY5pglszq
6M8VBjunWnq8ASZ2QDvjf/2lnrxpQhpIHtc4eI2vKx0eHZNINjyhMCU1t5Fv3sL0
drXrmRiMcRVzKCbO+pEDHOebdGSh8W2uL80mTw21/JIkvZ9v3ku+bQi2xyvn+RS8
BsZuYwnpWVEqQgp+umC4TLovG6gKgkRFrGUEZK48TunMlA\u003d\u003d
\u003dZNsA
-----END PGP MESSAGE-----



```

**Comment by twiss** [comment]
The second message looks like it's URL-encoded for some reason (replaced `=` with `\u003d`). You could try URL-encoding the first message and see if it works then, as well.

**Comment by vejandla** [comment]
Can I just get get encrypted message without the BEGIN PGP and END PGP sections?

**Comment by sidtagirisa** [comment]
@vejandla Hi, were you ever able to solve this issue? having the same issue while trying to communicate with API.
