### ISSUE TITLE
[BUG] Error encrypting message: key.getPrimaryUser is not a function

### ISSUE THREAD

**Issue by cojack** [openpgpjs/openpgpjs#1193]
```javascript
var openpgp = require("openpgp");

const publicKeyArmored = `-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBF/kvpQBCACmtlhZFpHKdq/08GLTaTcdjrO63uOJEVTbywt1tFCFNYGUeCCn
kNsU7d/w1nvOjDA4QOv1Zza3laLwj0skB03q3HFlZ5qG7gUmncRDGtEVA48Bzx5y
4dsRpovDB/QU0+c6AlRuCPbmEvKsm6+0vmDCr0EnoCK3HSPwzUhjTyqhnIjN/IxN
KgSq3QXRylRPhRD+d8O+8c/ZYoYc48fVmEg+9uBIammzt9nt2NT5Xfw2baCkE/Qq
Iw6bUlQuY1kNnxikoh5k6Ty9+v6sE0e0lTccaBJjoUc5YXLWVxsGetQcaqRWh5lQ
BUhBZFaYAoAfWygB8snBdo86MxtorUWKUE4fABEBAAG0B3F3ZUBxd2WJARwEEAEC
AAYFAl/kvpQACgkQDPZCGNGDd1Q66wf8DUJi2Kx3QAYircObtV24AV7f1nO7vgIE
stzGmWzGgw+UwrHVR4WKsWTxDQ9sbrb0/B06eMn8Y8SEh+YoQGVmHh6SPoirOno/
CSZIqkGXjitD25kS2kms602rxU+NDJuAxjU2mCZgVwCjXaMObNB0qe6DLyyoGQ2m
3AP2D2l3DliHuYw3niXaM3bEb4gcumEVi1vSEWL4fO1boqKhii4ZSBakzJ5dzCu/
YJmdeGBDP8TZ0ROzQM+CWx5+wWmaWayY9eTC7JZwouW68VzKSx+8BJi7JkVQSUso
cnQpZsFcrOVIzYMYPRswCYB9fneal3E5kz3tl7b4XHbhad8rKDnLBA==
=noiN
-----END PGP PUBLIC KEY BLOCK-----
`;

(async () => {
    await openpgp.initWorker({ path: 'openpgp.worker.js' });
    const publickKey = await openpgp.key.readArmored(publicKeyArmored);

    const { data: encrypted } = await openpgp.encrypt({
        message: openpgp.message.fromText('Hello, World!'),                 // input as Message object
        publicKeys: publickKey
    });
    
    console.log(encrypted);
})();
```

Error:
```
/home/cojack/Projects/private/opengpg/node_modules/openpgp/dist/openpgp.js:33998
    const primaryUser = await key.getPrimaryUser(date, userIds[i]);
                                  ^

TypeError: Error encrypting message: key.getPrimaryUser is not a function
    at /home/cojack/Projects/private/opengpg/node_modules/openpgp/dist/openpgp.js:33998:35
    at Array.map (<anonymous>)
    at getPreferredAlgo (/home/cojack/Projects/private/opengpg/node_modules/openpgp/dist/openpgp.js:33997:26)
    at Message.encrypt (/home/cojack/Projects/private/opengpg/node_modules/openpgp/dist/openpgp.js:36373:96)
    at /home/cojack/Projects/private/opengpg/node_modules/openpgp/dist/openpgp.js:37274:20
    at async /home/cojack/Projects/private/opengpg/index.js:26:33
```

How it should works?

**Comment by cojack** [comment]
Documentation sucks, it should be:

```javascript
(async () => {
    await openpgp.initWorker({ path: 'openpgp.worker.js' });
    const publickKey = await openpgp.key.readArmored(publicKeyArmored);

    const { data: encrypted } = await openpgp.encrypt({
        message: openpgp.message.fromText('Hello, World!'),
        publicKeys: publickKey.keys // DIFFERENCE
    });
    
    console.log(encrypted);
})();
```
