### ISSUE TITLE
No keys, passwords, or session key provided (v5.0.0-3)

### ISSUE THREAD

**Issue by rafipiccolo** [openpgpjs/openpgpjs#1315]
this sample code extracted from the documentation now returns error on v5.0.0-3 :

Does parameter changed with new version ? the doc doesn't seem to have changed.

```
const openpgp = require('openpgp');
const fs = require('fs');

(async () => {
    const text = await fs.promises.readFile('xxxxx'); // the file i try to decrypt
    const privateKeyArmored = await fs.promises.readFile('xxxxx');
    const passphrase = 'xxxx';

    const privateKey = await openpgp.decryptKey({
        privateKey: await openpgp.readKey({ armoredKey: privateKeyArmored.toString() }),
        passphrase,
    });

    // failing here
    const message = await openpgp.readMessage({
        'binaryMessage': text,
    });

    const { data: decrypted, signatures } = await openpgp.decrypt({
        message,
        privateKeys: privateKey, // for decryption
    });

    console.log(decrypted); // 'Hello, World!'
})();
```

returns :
```
Error: Error encrypting message: No keys, passwords, or session key provided.
      at oc.encrypt (node_modules/openpgp/dist/node/openpgp.min.js:2:336933)
      at /usr/app/node_modules/openpgp/dist/node/openpgp.min.js:16:133698
      at async Object.encrypt (lib/gpg.js:97:23)
      at async Context.<anonymous> (test/gpg.test.js:11:19)
```

line 19 is openpgp.decrypt

**Comment by twiss** [comment]
Yeah, they did, see the release changelog (or #1299). We should update the README indeed. @alichry Do you feel like doing so?

**Comment by rafipiccolo** [comment]
This works :

decryptionKeys
```
const openpgp = require('openpgp');
const fs = require('fs');

(async () => {
    const text = await fs.promises.readFile('./exemples/prodfiles/SFPB0IV000001.270421.050610995'); // the file i try to decrypt
    const privateKeyArmored = await fs.promises.readFile(process.env.GPG_KEY);
    const passphrase = process.env.GPG_PASSPHRASE;

    const privateKey = await openpgp.decryptKey({
        privateKey: await openpgp.readKey({ armoredKey: privateKeyArmored.toString() }),
        passphrase,
    });

    // failing here
    const message = await openpgp.readMessage({
        'binaryMessage': text,
    });

    const { data: decrypted, signatures } = await openpgp.decrypt({
        message,
        decryptionKeys: privateKey, // for decryption
    });

    console.log(decrypted); // 'Hello, World!'
})();
```

**Comment by alichry** [comment]
Hello @twiss @rafipiccolo 👋

Yes, I would be happy to. I can push a PR in about a week if that's okay ✌️
