### ISSUE TITLE
using encrypt with `format: 'armor'` gives error

### ISSUE THREAD

**Issue by tripodsan** [openpgpjs/openpgpjs#1389]
- OpenPGP.js version: 5.0.0-5
- Affected platform: Nodejs

according to https://github.com/openpgpjs/openpgpjs/pull/1354, the new way to specifying an armored result is with `format: 'amor'`. but using this results in:

```
Error: Unsupported format armor
    at yc (node_modules/openpgp/dist/node/openpgp.min.js:2:344670)
    at Object.exports.encrypt (node_modules/openpgp/dist/node/openpgp.min.js:16:134283)
```

**Comment by tripodsan** [comment]
ah, it was renamed to `armored`. nevermind.
