### ISSUE TITLE
Opengpg Parsing AppArmor

### ISSUE THREAD

**Issue by Mick2003** [openpgpjs/openpgpjs#1416]
- OpenPGP.js version: 5.0
- Affected platform (Browser or Node.js version): Firefox ( other platofrms? )

Dear reader,

When using the example from openpgp.js "Encrypt and decrypt String data with PGP keys", the readKey function gives back an error. 

Normally it would say there is missing an blank line in the pubArmoredKey, i fixed this by adding an enter in the backticks (or adding '\n' manually). 

After i've done that it gives back another error:

```
Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Y (http://localhost/HTML5application/scripts/openpgp.min.js:2:18207)
    at http://localhost/HTML5application/scripts/openpgp.min.js:2:17819
    at http://localhost/HTML5application/scripts/openpgp.min.js:2:6330
```

Anyone encounterd this bug and fixed it?

Kind Regards,

Mick2003

**Comment by Mick2003** [comment]
Don't know what the real fix is... Used keygeneration and added it that way.
