### ISSUE TITLE
use gopenpgp key pair tip Unknown signature subpacket type 39

### ISSUE THREAD

**Issue by kuaifan** [openpgpjs/openpgpjs#1621]
- OpenPGP.js version: v5.7.0
- Affected platform (Browser or Node.js version): 111.0.5563.110

使用

```
[OpenPGP.js debug] Error: Unknown signature subpacket type 39
    at Jc.readSubPacket (signature.js:523:25)
    at Jc.readSubPackets (signature.js:544:12)
    at Jc.read (signature.js:122:15)
    at packetlist.js:83:28
    at pi (packet.js:282:13)
    at async packetlist.js:100:11
```

**Comment by kuaifan** [comment]
Supplement the public key

-----------

-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: https://gopenpgp.org
Version: GopenPGP 2.6.1

xjMEXNlzAxYJKwYBBAHaRw8BAQdAjWBsNsFdhM89OOWn/5WAv1T49pPRCJWZimDb
SFpoG1nNK01heCBNdXN0ZXJtYW5uIDxtYXgubXVzdGVybWFubkBleGFtcGxlLmNv
bT7CjAQTFggAPgUCXNlzAwmQxtm0N6Z+mIIWIQSMf661y7WoHC9PbdXG2bQ3pn6Y
ggIbAwIeAQIZAQILBwIVCAMWAAIDJwcCAADXowEAzH11rIqj0yvKALPRVOuOS/dv
mO7PasBdavtm6yaOc5UA/3bHYxKoBiwvM1q3W6o8cuNlc7/+BfzT5WgyEBbBwFsM
zjgEXNlzAxIKKwYBBAGXVQEFAQEHQFqXs4dKdsG8AI8Tl6AqaGMyT+oy61uphkN7
9qK7TD4mAwEKCcJ4BBgWCAAqBQJc2XMDCZDG2bQ3pn6YghYhBIx/rrXLtagcL09t
1cbZtDemfpiCAhsMAAAtpwD/QTmehwRP6QRWbxN3mU1jRTWcd/hQxHeODTuwTHjy
JKIA/iDnI2UGV3YSmbDYKYgp7uoIoPfvJ5d3fNWN/s6GZysA
=5KJp
-----END PGP PUBLIC KEY BLOCK-----
