### ISSUE TITLE
Decryption Error On Node v20.14.0 (LTS)

### ISSUE THREAD

**Issue by daltonwallace** [openpgpjs/openpgpjs#1760]
- OpenPGP.js version: v5.11.1
- Affected platform (Browser or Node.js version): v20.14.0 (LTS)

**Decryption succeeds** but console outputs the following error message:

```
[OpenPGP.js debug] Error: Decryption error
    at /Users/username/Code/projectname/node_modules/openpgp/dist/node/openpgp.min.js:2:178461
    at async Object.decrypt (/Users/username/Code/project/node_modules/openpgp/dist/node/openpgp.min.js:2:177833)
    at async ju.decrypt (/Users/username/Code/projectname/node_modules/openpgp/dist/node/openpgp.min.js:2:291055)
    at async /Users/username/Code/projectname/node_modules/openpgp/dist/node/openpgp.min.js:2:345538
    at async Promise.all (index 0)
    at async /Users/username/Code/projectname/node_modules/openpgp/dist/node/openpgp.min.js:2:344874
    at async Promise.all (index 0)
    at async /Users/username/Code/projectname/node_modules/openpgp/dist/node/openpgp.min.js:2:344484
    at async Promise.all (index 0)
    at async Bh.decryptSessionKeys (/Users/username/Code/projectname/node_modules/openpgp/dist/node/openpgp.min.js:2:344441)```

**Comment by daltonwallace** [comment]
These errors output all over the unit tests as well when run against 20.14.0
