### ISSUE TITLE
Unexpected exception with newer node18/node20 runtimes in AWS

### ISSUE THREAD

**Issue by lcampalvazqu** [openpgpjs/openpgpjs#1770]
Related to closed issue 1750
- OpenPGP.js version: 5.11.2 (also happened in 5.0.1)
- Affected platform (Browser or Node.js version): nodejs18.x nodejs20.x

When decrypting a file that have been working like 2 months ago, failure is related to newer revisions of the runtime, happens in both node18 and node20:

Tested on different private keys rsa3072 and multiple pgp files:

Unexpected exception while processing event Error: Error decrypting message: Decryption error
    at /var/task/node_modules/openpgp/dist/node/openpgp.min.js:2:178403
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Nu.decrypt (/var/task/node_modules/openpgp/dist/node/openpgp.min.js:2:290625)
    at async /var/task/node_modules/openpgp/dist/node/openpgp.min.js:2:345287
    at async Promise.all (index 0)
    at async /var/task/node_modules/openpgp/dist/node/openpgp.min.js:2:344623
    at async Promise.all (index 0)
    at async /var/task/node_modules/openpgp/dist/node/openpgp.min.js:2:344233
    at async Promise.all (index 0)
    at async Ih.decryptSessionKeys (/var/task/node_modules/openpgp/dist/node/openpgp.min.js:2:344190)

**Comment by larabr** [comment]
Hi, please double check you are indeed using v5.11.1 or newer, I cannot repro the error.
