### ISSUE TITLE
Encrypt method doesn't work on Deno

### ISSUE THREAD

**Issue by ButterDebugger** [openpgpjs/openpgpjs#1813]
OpenPGP.js version: 6.0.1
Affected platform: Deno v2.1.3

Encrypting a message throws an error but only when using Deno

I have openpgp imported with `npm:openpgp@^6.0.1` and `nodeModulesDir` set to `auto`
The error may be due to a compatibility issue between OpenPGP.js and Deno's native crypto API

This is the code I have written:

```js
import { generateKey, readKey, createMessage, encrypt } from "openpgp";

// Generate a new RSA key pair with specified options
const { publicKey, _privateKey } = await generateKey({
	type: "rsa",
	rsaBits: 2048,
	userIDs: [
		{
			name: "John Doe",
		},
	],
	format: "armored",
});

// Create a message to be encrypted
const messageBody = await createMessage({
	text: "Hello, world!",
});

// Read the public key
const encryptionKey = await readKey({
	armoredKey: publicKey,
});

// Encrypt the message using the public key
// But instead of returning the encrypted message, it throws an error
const encryptedMessage = await encrypt({
	message: messageBody,
	encryptionKeys: encryptionKey,
	format: "armored",
});

// Output the encrypted message to the console
console.log(encryptedMessage);

```

This is the error I am getting:

```c
error: Uncaught (in promise) TypeError: Error encrypting message: Invalid key type                                                                                                  
    at prepareKey (ext:deno_node/internal/crypto/cipher.ts:234:13)                                                                                                                  
    at Object.publicEncrypt (ext:deno_node/internal/crypto/cipher.ts:218:20)                                                                                                        
    at nodeEncrypt (file:///C:/Users/Jupiter/Desktop/test/node_modules/.deno/openpgp@6.0.1/node_modules/openpgp/dist/node/openpgp.mjs:6364:38)                                       
    at Object.encrypt$4 [as encrypt] (file:///C:/Users/Jupiter/Desktop/test/node_modules/.deno/openpgp@6.0.1/node_modules/openpgp/dist/node/openpgp.mjs:6126:12)
    at Object.publicKeyEncrypt (file:///C:/Users/Jupiter/Desktop/test/node_modules/.deno/openpgp@6.0.1/node_modules/openpgp/dist/node/openpgp.mjs:10834:37)
    at PublicKeyEncryptedSessionKeyPacket.encrypt (file:///C:/Users/Jupiter/Desktop/test/node_modules/.deno/openpgp@6.0.1/node_modules/openpgp/dist/node/openpgp.mjs:15007:34)       
    at file:///C:/Users/Jupiter/Desktop/test/node_modules/.deno/openpgp@6.0.1/node_modules/openpgp/dist/node/openpgp.mjs:19816:29
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async Promise.all (index 0)
    at async Function.encryptSessionKey (file:///C:/Users/Jupiter/Desktop/test/node_modules/.deno/openpgp@6.0.1/node_modules/openpgp/dist/node/openpgp.mjs:19805:23)
```

**Comment by larabr** [comment]
Interesting, thanks for reporting. It seems Deno has yet to implement support for KeyObjects (which we integrated in #1722 ): https://github.com/denoland/deno/blob/65db8814c31464f2bc2a04dd5ffbaa71361c9f80/ext/node/polyfills/internal/crypto/cipher.ts#L409 .

Could you open an issue with them about this?
I can patch this on our side for now, but it's not ideal as we would probably have to use the JS fallback code instead of the native crypto implementation .

**Comment by twiss** [comment]
As a workaround, you could try to use the browser build? That one uses the Web Crypto API, instead.

You'd have to do something like:
```js
import ... from 'openpgp/dist/openpgp.min.mjs';
```

Also, do you need to use 2048-bit RSA keys? The default Curve25519 keys are more secure, and might work as well (haven't tested though).
