### ISSUE TITLE
Imperative global error handler

### ISSUE THREAD

**Issue by exos** [openpgpjs/openpgpjs#341]
Hi, I don't know if catalogate this as error, but is realy annoying:

When I call ```OpenPGP.decryptAndVerifyMessage``` (among others) method, I spect the error on the catch callback of promise. This works, but there are a errback on ```execute``` promise that log the error trace and throw it no matter the option ```config.debug```. This is annoying when 
it expected an error.

In openpgp.js, line 280 there are:
```JavaScript
/**
 * Command pattern that wraps synchronous code into a promise
 * @param  {function} cmd     The synchronous function with a return value
 *                            to be wrapped in a promise
 * @param  {String}   errMsg  A human readable error Message
 * @return {Promise}          The promise wrapped around cmd
 */
function execute(cmd, errMsg) {
  // wrap the sync cmd in a promise
  var promise = new Promise(function(resolve) {
    var result = cmd();
    resolve(result);
  });

  // handler error globally
  return promise.catch(onError.bind(null, errMsg));
}

/**
 * Global error handler that logs the stack trace and
 *   rethrows a high lvl error message
 * @param  {String} message   A human readable high level error Message
 * @param  {Error}  error     The internal error that caused the failure
 */
function onError(message, error) {
  // log the stack trace
  console.error(error.stack);
  // rethrow new high level error for api users
  throw new Error(message);
}
```

In my case, I try to decrypt a message with several keys, knowing that some will fail.  The result of throw it (and logging it) is a unnecessary output on my app, and unit tests. 

For example:

```
[4mRunning "simplemocha:all" (simplemocha) task[24m


  Test block creation from content

    ✓ Geting private key (363ms)

    ✓ Syncing block model (132ms)

    ✓ Creating block from ciphered content (134ms)

    ✓ Creating block from lorem (5060ms)
Error: Decryption error
    at Object.module.exports.eme.decode (/home/exos/alpha/xinara/src/xinara-lib/node_modules/openpgp/src/crypto/pkcs1.js:122:15)
    at PublicKeyEncryptedSessionKey.decrypt (/home/exos/alpha/xinara/src/xinara-lib/node_modules/openpgp/src/packet/public_key_encrypted_session_key.js:172:34)
    at Message.decrypt (/home/exos/alpha/xinara/src/xinara-lib/node_modules/openpgp/src/message.js:104:21)
    at /home/exos/alpha/xinara/src/xinara-lib/node_modules/openpgp/src/openpgp.js:172:15
    at /home/exos/alpha/xinara/src/xinara-lib/node_modules/openpgp/src/openpgp.js:290:18
    at execute (/home/exos/alpha/xinara/src/xinara-lib/node_modules/openpgp/src/openpgp.js:289:17)
    at Object.decryptAndVerifyMessage (/home/exos/alpha/xinara/src/xinara-lib/node_modules/openpgp/src/openpgp.js:170:10)
    at /home/exos/alpha/xinara/src/xinara-lib/lib/models/blocks.js:178:25
    at tryCatcher (/home/exos/alpha/xinara/src/xinara-lib/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/home/exos/alpha/xinara/src/xinara-lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:476:31)
    at new Promise (/home/exos/alpha/xinara/src/xinara-lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:69:37)
    at db.define.instanceMethods.checkWith (/home/exos/alpha/xinara/src/xinara-lib/lib/models/blocks.js:162:20)
    at null.<anonymous> (/home/exos/alpha/xinara/src/xinara-lib/test/blocks.js:111:23)
    at tryCatcher (/home/exos/alpha/xinara/src/xinara-lib/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/exos/alpha/xinara/src/xinara-lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/exos/alpha/xinara/src/xinara-lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)

    ✓ Try to decrypt block with INvalid key (3331ms)

    ✓ Try to decrypt block with valid key (2996ms)

  Checking keys model

    ✓ Sync model schema (261ms)

    ✓ Saving public key model (130ms)

    ✓ Try to save the same key

    ✓ Updating as private (161ms)

    ✓ Try to saving invalid key model

  Checking server model

    ✓ Sync model schema (258ms)

    ✓ Creating server (164ms)

    ✓ Try to create invalid url server


  14 passing (13s)


[32mDone, without errors.[39m
```

**Comment by tanx** [comment]
This is fixed in v2.x
