### ISSUE TITLE
Error encrypting message!

### ISSUE THREAD

**Issue by KCreate** [openpgpjs/openpgpjs#382]
When trying to encrypt, i get this error:
TypeError: keys[i].getPrimaryUser is not a function
    at Object.getPreferredSymAlgo (.../node_modules/openpgp/src/key.js:1017:31)
    at Message.encrypt (.../node_modules/openpgp/src/message.js:150:27)
    at .../node_modules/openpgp/src/openpgp.js:96:15
    at .../node_modules/openpgp/src/openpgp.js:290:18
    at execute (.../node_modules/openpgp/src/openpgp.js:289:17)
    at Object.encryptMessage (.../node_modules/openpgp/src/openpgp.js:93:10)
    at Object.<anonymous> (.../index.js:38:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
[Error: Error encrypting message!]

I'm using this code:
var openpgp = require('openpgp');

var key = '-----BEGIN PGP PUBLIC KEY BLOCK----- ... -----END PGP PUBLIC KEY BLOCK-----';
var publicKey = openpgp.key.readArmored(key);

openpgp.encryptMessage(publicKey.keys, 'Hello, World!').then(function(pgpMessage) {
    // success
	console.log(pgpMessage);
}).catch(function(error) {
    // failure
	console.log(error);
});

**Comment by gmontalvoriv** [comment]
You should try generating a new key pair using [openpgp.generateKeyPair](https://github.com/openpgpjs/openpgpjs#generate-new-keypair) and use the new public key instead to see if the problem persists. I found the same error when using a GnuPG/MacGPG2 v2.0.22 key. This could be a compatibility issue.

**Comment by tanx** [comment]
Please retry with v2.x
