### ISSUE TITLE
running openpgp.js in pure V8 engine - setTimeout recently broke

### ISSUE THREAD

**Issue by tomholub** [openpgpjs/openpgpjs#619]
We're running OpenPGP.js using a bare V8 engine with some Java bindings on Android (J2V8)

Recently, the JS code transpiles with a slight difference in how async code is handled:

v2.5.14
```js
    var lib$es6$promise$asap$$scheduleFlush;
    // Decide what async method to use to triggering processing of queued callbacks:
    if (lib$es6$promise$asap$$isNode) {
      lib$es6$promise$asap$$scheduleFlush = lib$es6$promise$asap$$useNextTick();
    } else if (lib$es6$promise$asap$$BrowserMutationObserver) {
      lib$es6$promise$asap$$scheduleFlush = lib$es6$promise$asap$$useMutationObserver();
    } else if (lib$es6$promise$asap$$isWorker) {
      lib$es6$promise$asap$$scheduleFlush = lib$es6$promise$asap$$useMessageChannel();
    } else if (lib$es6$promise$asap$$browserWindow === undefined && typeof _dereq_ === 'function') {
      lib$es6$promise$asap$$scheduleFlush = lib$es6$promise$asap$$attemptVertx();
    } else {
      lib$es6$promise$asap$$scheduleFlush = lib$es6$promise$asap$$useSetTimeout();
    }
```
https://github.com/openpgpjs/openpgpjs/blob/e7e18777b04ea730fd8cf7409fe4f0ef72b8cf65/dist/openpgp.js#L3083

compare v2.6.0: 
```js
var scheduleFlush = undefined;
// Decide what async method to use to triggering processing of queued callbacks:
if (isNode) {
  scheduleFlush = useNextTick();
} else if (BrowserMutationObserver) {
  scheduleFlush = useMutationObserver();
} else if (isWorker) {
  scheduleFlush = useMessageChannel();
} else if (browserWindow === undefined && typeof _dereq_ === 'function') {
  scheduleFlush = attemptVertx();
} else {
  scheduleFlush = useSetTimeout();
}
```
https://github.com/openpgpjs/openpgpjs/blob/2ffa221b214e9f89574152f2fb76363d50213b92/dist/openpgp.js#L3090

Looks harmless to me, but V8 cannot stomach it:

```
        java.lang.RuntimeException: Unable to create application com.flowcrypt.email.FlowCryptApplication: undefined:3058: ReferenceError: setTimeout is not defined
          var globalSetTimeout = setTimeout;
                                 ^
        ReferenceError: setTimeout is not defined
            at useSetTimeout (<anonymous>:3058:26)
            at <anonymous>:3101:19
            at type (<anonymous>:2954:82)
            at Object.<anonymous> (<anonymous>:2957:2)
            at Object.2._process (<anonymous>:4103:4)
            at s (<anonymous>:1:621)
            at <anonymous>:1:672
            at Object.43../cleartext.js (<anonymous>:15903:19)
            at s (<anonymous>:1:621)
            at <anonymous>:1:672
        com.eclipsesource.v8.V8ScriptExecutionException
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5405)
            at android.app.ActivityThread.-wrap2(ActivityThread.java)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:154)
            at android.app.ActivityThread.main(ActivityThread.java:6123)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
         Caused by: undefined:3058: ReferenceError: setTimeout is not defined
          var globalSetTimeout = setTimeout;
                                 ^
        ReferenceError: setTimeout is not defined
            at useSetTimeout (<anonymous>:3058:26)
            at <anonymous>:3101:19
            at type (<anonymous>:2954:82)
            at Object.<anonymous> (<anonymous>:2957:2)
            at Object.2._process (<anonymous>:4103:4)
            at s (<anonymous>:1:621)
            at <anonymous>:1:672
            at Object.43../cleartext.js (<anonymous>:15903:19)
            at s (<anonymous>:1:621)
            at <anonymous>:1:672
        com.eclipsesource.v8.V8ScriptExecutionException
            at com.eclipsesource.v8.V8._executeScript(Native Method)
            at com.eclipsesource.v8.V8.executeScript(V8.java:1061)
            at com.eclipsesource.v8.V8.executeScript(V8.java:668)
            at com.eclipsesource.v8.V8.executeScript(V8.java:651)
            at com.flowcrypt.email.js.Js.loadJavascriptCode(Js.java:313)
            at com.flowcrypt.email.js.Js.<init>(Js.java:67)
            at com.flowcrypt.email.js.JsForUiManager.<init>(JsForUiManager.java:35)
            at com.flowcrypt.email.js.JsForUiManager.getInstance(JsForUiManager.java:55)
            at com.flowcrypt.email.js.JsForUiManager.init(JsForUiManager.java:48)
            at com.flowcrypt.email.FlowCryptApplication.onCreate(FlowCryptApplication.java:72)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1046)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5402)
            	... 8 more
```

Any idea what triggered the change?

**Comment by bartbutler** [comment]
It must have been a transpiler update, which would be this commit:

https://github.com/openpgpjs/openpgpjs/commit/31d381fb277399a05209ef3a64df809211e3351d

Definitely mystifying though, it looks like a totally benign change.

**Comment by tomholub** [comment]
The new transpiler version may have some settings to turn certain features
off, etc. Maybe I can isolate it to figure out which setting would produce
something similar to the original code, or just something that works.

In addition, I'll see if there is a way to add non-node V8 runtime test as
part of the tests. We're relying on this stuff, so it would be great to
include our runtime in the tests.

Do we need to coordinate anything other than me making a pr to edit Travis
config files in the repo? Never worked with Travis before.

On Jan 6, 2018 7:10 PM, "Bart Butler" <notifications@github.com> wrote:

It must have been a transpiler update, which would be this commit:

31d381f
<https://github.com/openpgpjs/openpgpjs/commit/31d381fb277399a05209ef3a64df809211e3351d>

Definitely mystifying though, it looks like a totally benign change.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openpgpjs/openpgpjs/issues/619#issuecomment-355764696>,
or mute the thread

**Comment by bartbutler** [comment]
Nope, I think the repo config files are it, but @evilaliv3 is a better person to ask that question.

**Comment by tomholub** [comment]
Just a note, please don't close this one for me, wasn't able to get to it yet :-/

**Comment by spearmootz** [comment]
i dont think you will solve this. i think (could be wrong) that any async functionality is provided outside the v8 engine. so setTimeout, setInterval or any promise wont work.... i am saying i could be wrong

**Comment by tomholub** [comment]
We are using previous versions in J2V8. Promises work just fine, only setTimeout is missing. They do seem to have some facilities for this.

**Comment by tomholub** [comment]
No longer relevant

**Comment by tomholub** [comment]
No longer relevant
