### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by vnndi** [openpgpjs/openpgpjs#700]
Right from the code from openpgp docs:
```
var privKeyObj = openpgp.key.readArmored(privkey).keys[0];
await privKeyObj.decrypt(passphrase);
 
options = {
    data: 'Hello, World!',                             // input as String (or Uint8Array)
    publicKeys: openpgp.key.readArmored(pubkey).keys,  // for encryption
    privateKeys: [privKeyObj]                          // for signing (optional)
};
 
openpgp.encrypt(options).then(function(ciphertext) {
    encrypted = ciphertext.data; // '-----BEGIN PGP MESSAGE ... END PGP MESSAGE-----'
});
```

```
SyntaxError: await is only valid in async function
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
```

I tried to put the code after `await` inside a `.then()` but it doesn't work. I've also tried what recommended here: https://stackoverflow.com/questions/46159415/await-promises-all-syntaxerror

**Comment by tomholub** [comment]
You can put your code inside an async wrapper, like so:
```js
(async() => {

    // your code
    // ...

})();
```

**Comment by vnndi** [comment]
If I do this:
```
const openpgp = require('openpgp'); // use as CommonJS, AMD, ES6 module or via window.openpgp
openpgp.initWorker({ path:'openpgp.worker.js' })

(async() => {
    
    const privKeyObj = openpgp.key.readArmored(privkey).keys[0];
    await privKeyObj.decrypt(passphrase);
    
    options = {
        data: 'Hello, World!',                             // input as String (or Uint8Array)
        publicKeys: openpgp.key.readArmored(pubkey).keys,  // for encryption
        privateKeys: [privKeyObj]                          // for signing (optional)
    };
    
    openpgp.encrypt(options).then(function(ciphertext) {
        encrypted = ciphertext.data; // '-----BEGIN PGP MESSAGE ... END PGP MESSAGE-----'
    });
})();
```
I get this: 
```
(async() => {
^

TypeError: openpgp.initWorker(...) is not a function
```
If I move `openpgp.initWorker()` inside the `async()`, I get this:
`(node:14384) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'decrypt' of undefined`

**Comment by tomholub** [comment]
Where are you running this? In a browser, in Node?

**Comment by vnndi** [comment]
I run in Node. I'm trying to use this package to decrypt some .pgp files. I've got all the public and private key along with the passphrase.

**Comment by tomholub** [comment]
I don't think node has a web worker. Comment out/delete `openpgp.initWorker({ path:'openpgp.worker.js' })`

**Comment by vnndi** [comment]
I commented it out and I have this error:
```
if (input === null || input.length <= position || input.subarray(position, input.length).length < 2 || (input[position] & 0x80) === 0) {
                                                            ^

TypeError: input.subarray is not a function
```
and i know the file is not empty. I used gpg command from the terminal to decrypt it. However, I can only do it with the shell command, not in my Node app

**Comment by vnndi** [comment]
@tomholub Basically I just copied and pasted from the docs:
```
const openpgp = require('openpgp'); // use as CommonJS, AMD, ES6 module or via window.openpgp
 
openpgp.initWorker({ path:'openpgp.worker.js' }) // set the relative web worker path
 
const pubkey = require('<path to file>');
const privkey = require('<path to file>'); //encrypted private key
const passphrase = require('<path to file>'); //what the privKey is encrypted with
 
const privKeyObj = openpgp.key.readArmored(privkey).keys[0];
await privKeyObj.decrypt(passphrase);
 
const options = {
    data: 'Hello, World!',                             // input as String (or Uint8Array)
    publicKeys: openpgp.key.readArmored(pubkey).keys,  // for encryption
    privateKeys: [privKeyObj]                          // for signing (optional)
};
 
openpgp.encrypt(options).then(function(ciphertext) {
    encrypted = ciphertext.data; // '-----BEGIN PGP MESSAGE ... END PGP MESSAGE-----'
});
```
I've tested my both my public and private key and passphrase with `gpg` in the shell and all my `.pgp` files are not corrupt, properly encrypted and `gpg` successfully decrypted them.
I'm trying to encrypt and decrypt my files using this Nodejs package, hence the question I have here.

**Comment by vnndi** [comment]
full stack trace (if I comment out await):
```
(node:13387) UnhandledPromiseRejectionWarning: TypeError: Error encrypting message: Cannot read property 'isPublic' of undefined
    at _callee12$ (<path>/node_modules/openpgp/dist/openpgp.js:42248:41)
    at tryCatch (<path>/node_modules/openpgp/dist/openpgp.js:25189:40)
    at Generator.invoke [as _invoke] (<path>/node_modules/openpgp/dist/openpgp.js:25423:22)
    at Generator.prototype.(anonymous function) [as next] (<path>/node_modules/openpgp/dist/openpgp.js:25241:21)
    at step (<path>/node_modules/openpgp/dist/openpgp.js:3744:30)
    at <path>/node_modules/openpgp/dist/openpgp.js:3762:14
    at new Promise (<anonymous>)
    at new F (/<path>/node_modules/openpgp/dist/openpgp.js:9550:28)
    at <path>/node_modules/openpgp/dist/openpgp.js:3741:12
    at <path>/node_modules/openpgp/dist/openpgp.js:42295:31
(node:13387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13387) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by vnndi** [comment]
Thanks @tomholub for the suggestion. I removed that and put the keys as variables in the code itself and I got this error:
```
(node:28393) UnhandledPromiseRejectionWarning: Error: Error encrypting message: Private key is not decrypted.
    at _callee15$ (<path>/node_modules/openpgp/dist/openpgp.js:41365:31)
    at tryCatch (<path>/node_modules/openpgp/dist/openpgp.js:25189:40)
    at Generator.invoke [as _invoke] (<path>/node_modules/openpgp/dist/openpgp.js:25423:22)
    at Generator.prototype.(anonymous function) [as next] (<path>/node_modules/openpgp/dist/openpgp.js:25241:21)
    at step (<path>/node_modules/openpgp/dist/openpgp.js:3744:30)
    at <path>/node_modules/openpgp/dist/openpgp.js:3755:13
    at process._tickCallback (internal/process/next_tick.js:178:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
(node:28393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28393) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
it seems like `await privKeyObj.decrypt(passphrase);` needs to be there but if I don't comment it out, it'll give me the same error I had before this one

**Comment by vnndi** [comment]
Hey @tomholub Never mind my comment above, after some tweaking, I've been able to make it work. Thank you so much for your help.
