### ISSUE TITLE
Throw error when using non-decrypted key to sign things

### ISSUE THREAD

**Issue by indutny** [openpgpjs/openpgpjs#701]
Currently, the library throws intangible error message when attempting to use non-decrypted private key for creating signatures:

```
TypeError: Cannot read property 'toBN' of undefined
    at Object._callee2$ (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:37192:33)
    at tryCatch (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:26637:40)
    at Generator.invoke [as _invoke] (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:26871:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:26689:21)
    at step (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:4012:30)
    at /Users/findutnyy/Code/openpgpjs/dist/openpgp.js:4030:14
    at new Promise (<anonymous>)
    at new F (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:9832:28)
    at Object.<anonymous> (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:4009:12)
    at Object.sign (/Users/findutnyy/Code/openpgpjs/dist/openpgp.js:37250:20)
```

**Comment by indutny** [comment]
Nvm, this was my code.
