### ISSUE TITLE
pc2bytes0 is not defined at des_createKeys 

### ISSUE THREAD

**Issue by QAnders** [openpgpjs/openpgpjs#809]
Anyone seen this before and know of a solution?

```
ReferenceError: pc2bytes0 is not defined at des_createKeys (local:///openpgpjs/crypto/cipher/des.js:234:13) at Des.encrypt (local:///openpgpjs/crypto/cipher/des.js:376:29) at Object.module.exports.decrypt (local:///openpgpjs/crypto/cfb.js:188:23) at SymmetricallyEncrypted.decrypt (local:///openpgpjs/packet/symmetrically_encrypted.js:65:30) at Message.decrypt (local:///openpgpjs/message.js:112:26) at local:///openpgpjs/openpgp.js:165:15 at local:///openpgpjs/openpgp.js:311:18 at execute (local:///openpgpjs/openpgp.js:310:17) at Object.decryptMessage (local:///openpgpjs/openpgp.js:164:10) at pgpDecryptMsg (local:///GWS/pgp_encryption.js:56:10)
```

**Comment by QAnders** [comment]
Never mind... old version of des.js...
