### ISSUE TITLE
Web Worker Out of Memory

### ISSUE THREAD

**Issue by steverecio** [openpgpjs/openpgpjs#852]
I just tried moving my in-browser implementation to a web worker to free up the main js event loop and I'm getting the following error when trying to encrypt large files:

`Failed to execute 'postMessage' on 'Worker': Data cannot be cloned, out of memory.`

My code without the web worker successfully handles arbitrarily large files (although the page becomes unresponsive until encryption completes).

Here are the two versions of my code (running within a react application)

W/o web worker:

```
import { Buffer } from 'buffer';
import * as openpgp from 'openpgp';
```

With web worker (causes OOM error):

```
import { Buffer } from 'buffer';
var openpgp = require('openpgp');
openpgp.initWorker({ path: '/openpgp.worker.js' })
```

Common code path:

```
export const encryptFileOpenPGP = (file, pubkey, callback_func) => {
  const filename = file.name;
  const r = new FileReader();
  r.readAsArrayBuffer(file);
  r.onloadend = async file => {
    var result = r.result;
    var buffer = Buffer.from(result);

    const options = {
      message: openpgp.message.fromBinary(buffer, filename),
      publicKeys: (await openpgp.key.readArmored(pubkey)).keys,
      compression: openpgp.enums.compression.zip,
      armor: false
    };

    openpgp.encrypt(options).then(function(ciphertext) {
      var encrypted = ciphertext.message.packets.write(); // get raw encrypted packets as Uint8Array
      callback_func(encrypted);
    });
  };
};
```

Stacktrace (error stems from `openpgp.encrypt(options)`):

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': Data cannot be cloned, out of memory.
    at _callee259$ (http://localhost:3000/static/js/0.chunk.js:87274:47)
    at tryCatch (http://localhost:3000/static/js/0.chunk.js:145556:17)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/0.chunk.js:145775:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/0.chunk.js:145609:21)
    at asyncGeneratorStep (http://localhost:3000/static/js/0.chunk.js:17001:24)
    at _next (http://localhost:3000/static/js/0.chunk.js:17023:9)
    at http://localhost:3000/static/js/0.chunk.js:17030:7
    at new Promise (<anonymous>)
    at http://localhost:3000/static/js/0.chunk.js:17019:12
    at http://localhost:3000/static/js/0.chunk.js:87298:28
    at new Promise (<anonymous>)
    at AsyncProxy.delegate (http://localhost:3000/static/js/0.chunk.js:87263:16)
    at Object.encrypt (http://localhost:3000/static/js/0.chunk.js:77019:29)
    at FileReader._callee$ (http://localhost:3000/static/js/main.chunk.js:9675:23)
    at tryCatch (http://localhost:3000/static/js/0.chunk.js:145556:17)
    at Generator.invoke [as _invoke] (http://localhost:3000/static/js/0.chunk.js:145775:22)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:3000/static/js/0.chunk.js:145609:21)
    at asyncGeneratorStep (http://localhost:3000/static/js/0.chunk.js:17131:24)
    at _next (http://localhost:3000/static/js/0.chunk.js:17153:9)
```

**Comment by steverecio** [comment]
This came down to using readableStreams. Solved the problem. No more OOM killer.
