### ISSUE TITLE
Unable to load module openpgp in nodejs

### ISSUE THREAD

**Issue by pri1090** [openpgpjs/openpgpjs#859]
Hi, I am trying to load the openpgp module in nodej with the below code:

const openpgp = require('openpgp');

And soon as I build my project with that I get the below error:
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/utility.js:2:17)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)

My project is deployed on AWS and I am using gulp to build and package it.
I am spent almost a day trying to find a fix ..but unable to. I know for sure that loading this module causes an error as the moment I comment that line it works normally without any error. 

Would appreciate a lot if someone can guide me through.

**Comment by twiss** [comment]
If you search for that error online, there's plenty of people having the same issue on AWS. Please try some of the suggestions there. It seems unlikely that this is an issue in openpgp as requiring it locally in node works fine. Good luck!
